import type { BuildingDef, BuildingType, ResourceType } from './types';

export const BUILDING_DEFS: Record<BuildingType, BuildingDef> = {
  house: {
    type: 'house',
    category: 'housing',
    label: 'House',
    emoji: '🏠',
    cost: { wood: 2 },
    labor: 1,
  },
  dirt_path: {
    type: 'dirt_path',
    category: 'road',
    label: 'Dirt path',
    emoji: '🟫',
    cost: {},
  },
  road: {
    type: 'road',
    category: 'road',
    label: 'Road',
    emoji: '🛤️',
    cost: {},
  },
  highway: {
    type: 'highway',
    category: 'road',
    label: 'Highway',
    emoji: '🛣️',
    cost: {},
  },
  forum: {
    type: 'forum',
    category: 'civic',
    label: 'Forum',
    emoji: '🏛️',
    cost: { rock: 4, wood: 2 },
    labor: 2,
  },
  tree: {
    type: 'tree',
    category: 'decorative',
    label: 'Tree',
    emoji: '🌳',
    cost: {},
  },
  clay_pit: {
    type: 'clay_pit',
    category: 'natural_extractor',
    label: 'Clay pit',
    emoji: '🟤',
    cost: {},
    requiredDeposit: 'clay',
    outputs: { clay: 2 },
    labor: 1,
  },
  quarry: {
    type: 'quarry',
    category: 'natural_extractor',
    label: 'Quarry',
    emoji: '⛏️',
    cost: {},
    requiredDeposit: 'rock',
    outputs: { rock: 2 },
    labor: 1,
  },
  sand_pit: {
    type: 'sand_pit',
    category: 'natural_extractor',
    label: 'Sand pit',
    emoji: '🏖️',
    cost: {},
    requiredDeposit: 'sand',
    outputs: { sand: 2 },
    labor: 1,
  },
  iron_mine: {
    type: 'iron_mine',
    category: 'natural_extractor',
    label: 'Iron mine',
    emoji: '⚙️',
    cost: { wood: 4 },
    requiredDeposit: 'iron',
    outputs: { iron: 1 },
    labor: 2,
  },
  gold_mine: {
    type: 'gold_mine',
    category: 'natural_extractor',
    label: 'Gold mine',
    emoji: '👑',
    cost: { wood: 6, iron: 2 },
    requiredDeposit: 'gold',
    outputs: { gold: 1 },
    labor: 3,
  },
  lumber_camp: {
    type: 'lumber_camp',
    category: 'natural_extractor',
    label: 'Lumber camp',
    emoji: '🪓',
    cost: {},
    requiredDeposit: 'trees',
    outputs: { wood: 2 },
    labor: 1,
  },
  farm_wheat: {
    type: 'farm_wheat',
    category: 'farm',
    label: 'Wheat farm',
    emoji: '🌾',
    cost: { wood: 1 },
    outputs: { wheat: 2 },
    labor: 1,
  },
  pottery_workshop: {
    type: 'pottery_workshop',
    category: 'factory',
    label: 'Pottery',
    emoji: '🏺',
    cost: { wood: 3, rock: 2 },
    inputs: { clay: 2 },
    outputs: { pottery: 1 },
    labor: 2,
  },
  weaponsmith: {
    type: 'weaponsmith',
    category: 'factory',
    label: 'Weaponsmith',
    emoji: '⚔️',
    cost: { wood: 4, iron: 3 },
    inputs: { iron: 2, wood: 1 },
    outputs: { weapons: 1 },
    labor: 3,
  },
  warehouse: {
    type: 'warehouse',
    category: 'storage',
    label: 'Warehouse',
    emoji: '📦',
    cost: { wood: 6, rock: 4 },
    labor: 1,
  },
  shrine: {
    type: 'shrine',
    category: 'religion',
    label: 'Shrine',
    emoji: '⛩️',
    cost: { rock: 2, wood: 2 },
    labor: 1,
  },
  temple: {
    type: 'temple',
    category: 'religion',
    label: 'Temple',
    emoji: '🏛️',
    cost: { rock: 6, wood: 4, pottery: 2 },
    inputs: { wine: 1 },
    labor: 2,
  },
  oracle: {
    type: 'oracle',
    category: 'religion',
    label: 'Oracle',
    emoji: '🔮',
    cost: { rock: 8, gold: 2, pottery: 2 },
    labor: 3,
  },
  trade_post: {
    type: 'trade_post',
    category: 'trade',
    label: 'Trade post',
    emoji: '🏪',
    cost: { wood: 8, rock: 4 },
    labor: 2,
  },
  market: {
    type: 'market',
    category: 'trade',
    label: 'Market',
    emoji: '🛒',
    cost: { wood: 6, rock: 2 },
    labor: 1,
  },
  dock: {
    type: 'dock',
    category: 'trade',
    label: 'Dock',
    emoji: '⚓',
    cost: { wood: 10, rock: 6 },
    labor: 2,
  },
};

export function getBuildingDef(type: BuildingType): BuildingDef {
  return BUILDING_DEFS[type];
}

/** Maps extractor output resource back to deposit type for validation hints. */
export const DEPOSIT_TO_EXTRACTOR: Partial<
  Record<import('./types').NaturalDepositType, BuildingType>
> = {
  clay: 'clay_pit',
  rock: 'quarry',
  sand: 'sand_pit',
  iron: 'iron_mine',
  gold: 'gold_mine',
  trees: 'lumber_camp',
};

export const RESOURCE_EMOJI: Record<ResourceType, string> = {
  clay: '🟤',
  rock: '🪨',
  sand: '🏖️',
  wood: '🪵',
  iron: '⚙️',
  gold: '👑',
  wheat: '🌾',
  pottery: '🏺',
  weapons: '⚔️',
  olive_oil: '🫒',
  wine: '🍷',
};
